# Datasource configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/java_real_practice_insurance
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Mi656paspas

# JPA configuration (MySQL)
spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Blacklisted person check url
person.blacklisted.check.url=http://black-list-app:8080/blacklist/person/check